
eureka:
#  instance:
#    hostname: client
#    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

  client:
    service-url: # Eureka Server注册中心的地址, 用于Client与Server进行交流
      defaultZone: http://localhost:8100/eureka/

server:
  port: 8101
spring:
  application:
    name: bot-manager

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
    endpoints:
        web:
            exposure:
                include: "*"